In [6]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [19]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [20]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [21]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [22]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [23]:
arr = np.arange(12.).reshape((3, 4))

In [24]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
arr[0]

array([0., 1., 2., 3.])

In [30]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [31]:
frame

NameError: name 'frame' is not defined

In [32]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [41]:
series2 = Series(range(3), index=['b', 'e', 'f'])

In [42]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [43]:
frame - series2

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [44]:
series3 = frame['d']

In [45]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [46]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [47]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [48]:
np.abs(frame)

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [49]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [50]:
frame

b         d         e
Utah   -1.088811 -1.558431  0.659992
Ohio    0.831929 -0.900930 -0.403581
Texas   1.283692 -0.897760 -0.096085
Oregon -0.238765  1.202698  1.530620

In [51]:
np.abs(frame)

b         d         e
Utah    1.088811  1.558431  0.659992
Ohio    0.831929  0.900930  0.403581
Texas   1.283692  0.897760  0.096085
Oregon  0.238765  1.202698  1.530620

In [52]:
format = lambda x: '%.2f' % x

In [53]:
frame.applymap(format)

b      d      e
Utah    -1.09  -1.56   0.66
Ohio     0.83  -0.90  -0.40
Texas    1.28  -0.90  -0.10
Oregon  -0.24   1.20   1.53

In [54]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])

In [55]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [56]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],columns=['d', 'a', 'b', 'c'])

In [58]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [59]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [63]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [66]:
obj1 = Series([7, -5, 7, 4, 2, 0, 4])

In [67]:
obj1.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [69]:
obj1 = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [70]:
obj1

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [71]:
obj1.index.is_unique

False

In [74]:
obj1['a']

a    0
a    1
dtype: int64

In [75]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [76]:
df

0         1         2
a -0.786601 -0.035126 -0.238534
a  0.088093 -0.783170 -0.979970
b -1.668851  1.137901  0.646340
b  0.205442  0.173441  0.050003

In [78]:
df1 = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two'])

In [79]:
df1

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [80]:
df1.sum()

one    9.25
two   -5.80
dtype: float64

In [82]:
df1.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [84]:
df1.idxmax()

one    b
two    d
dtype: object

In [85]:
df1.idxmin()

one    d
two    b
dtype: object

In [86]:
uniques = obj.unique()

In [87]:
uniques

array([0, 1, 2, 3], dtype=int64)

In [88]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [90]:
obj3 = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])


In [91]:
obj3.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [98]:
obj3.value_counts()


a    3
c    3
b    2
d    1
dtype: int64

In [104]:
pd.value_counts(obj3.values, sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [105]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])


In [106]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [107]:
string_data.dropna()

0     aardvark
1    artichoke
3      avocado
dtype: object

In [108]:
from numpy import nan as NA
data = DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [109]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [110]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [111]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [112]:
string_data.fillna(0)

0     aardvark
1    artichoke
2            0
3      avocado
dtype: object

In [113]:
string_data.fillna("")

0     aardvark
1    artichoke
2             
3      avocado
dtype: object

In [114]:
data.fillna(0)

0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  6.5  3.0

In [115]:
data.fillna({1: 0.5, 3: -1})

0    1    2
0  1.0  6.5  3.0
1  1.0  0.5  NaN
2  NaN  0.5  NaN
3  NaN  6.5  3.0

In [116]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [117]:
data.fillna({1.0: 0.5, 6.5: -1})

0    1    2
0  1.0  6.5  3.0
1  1.0  0.5  NaN
2  NaN  0.5  NaN
3  NaN  6.5  3.0

In [119]:
data.fillna({0: 0.5, 2: 5})

0    1    2
0  1.0  6.5  3.0
1  1.0  5.0  NaN
2  0.5  5.0  NaN
3  0.5  6.5  3.0

In [121]:
data.fillna({0: 1, 1:3, 2: 5})

0    1    2
0  1.0  6.5  3.0
1  1.0  3.0  5.0
2  1.0  3.0  5.0
3  1.0  6.5  3.0

In [122]:
string_data


0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [124]:
data


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [125]:
data.fillna(data.mean())


0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [126]:
data = Series(np.random.randn(10), index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [127]:
data

a  1    0.307347
   2   -0.878660
   3   -1.546371
b  1    0.162552
   2   -0.826674
   3    0.019133
c  1   -0.610974
   2   -1.581614
d  2    0.298439
   3    0.401614
dtype: float64

In [128]:
data['b']

1    0.162552
2   -0.826674
3    0.019133
dtype: float64

In [129]:
data['b':'c']

b  1    0.162552
   2   -0.826674
   3    0.019133
c  1   -0.610974
   2   -1.581614
dtype: float64

In [130]:
data[:, 2]

a   -0.878660
b   -0.826674
c   -1.581614
d    0.298439
dtype: float64

In [131]:
data.unstack()

1         2         3
a  0.307347 -0.878660 -1.546371
b  0.162552 -0.826674  0.019133
c -0.610974 -1.581614       NaN
d       NaN  0.298439  0.401614

In [132]:
frame = DataFrame(np.arange(12).reshape((4, 3)), index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]], columns=[['Ohio', 'Ohio', 'Colorado'],['Green', 'Red', 'Green']])

In [133]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [135]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']

In [136]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [137]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [138]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [141]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16