In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.ndim

2

In [6]:
arr2.shape

(2, 4)

In [7]:
arr1.dtype

dtype('float64')

In [8]:
arr2.dtype

dtype('int32')

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [19]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [21]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [22]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr3[5]

5

In [27]:
arr3[5:8]

array([5, 6, 7])

In [28]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [29]:
arr2d[2]

array([7, 8, 9])

In [30]:
arr2d[0][2]

3

In [31]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [32]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr3d[0][1]

array([4, 5, 6])

In [36]:
arr3d[0][1][2]

6

In [37]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.sqrt(arr4)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [45]:
from numpy.random import randn
x = randn(8)
y = randn(8)
np.maximum(x, y)

array([ 2.87357297, -0.63570342,  1.38833604,  1.9176818 ,  0.76174069,
        0.02190272,  0.08497368,  1.62411265])

In [46]:
np.add(x,y)

array([ 4.318032  , -1.65530287,  0.29877784,  3.60789764,  0.64783749,
       -0.69563405, -0.82794344,  1.5680617 ])