In [4]:
# import numpy library
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

# importing linalg function from scipy
from scipy import linalg

# Compute the determinant of a matrix
linalg.det(A)



2.999999999999997

In [5]:
P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)
# print LU decomposition
print(np.dot(L,U))


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         8.        ]
 [0.         0.85714286 1.85714286]
 [0.         0.         0.5       ]]
[[7. 8. 8.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [6]:
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)
print(eigen_vectors)


[15.55528261+0.j -1.41940876+0.j -0.13587385+0.j]
[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]


In [7]:
v = np.array([[2],[3],[5]])
print(v)
s = linalg.solve(A,v)
print(s)


[[2]
 [3]
 [5]]
[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]


In [8]:
# import necessary modules
from scipy import sparse
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))
print(A)

A[0,:100] = np.random.rand(100)
A[1,100:200] = A[0,:100]
A.setdiag(np.random.rand(1000))
print(A)



  (0, 0)	0.6065115470409179
  (0, 1)	0.14322720794077404
  (0, 2)	0.9093801226285771
  (0, 3)	0.8531019040403952
  (0, 4)	0.3673078315709932
  (0, 5)	0.028969775007963605
  (0, 6)	0.3063952733001789
  (0, 7)	0.15452858085698162
  (0, 8)	0.9226297280469444
  (0, 9)	0.9426746514464875
  (0, 10)	0.21929454540633198
  (0, 11)	0.24927490717242295
  (0, 12)	0.6865400267790036
  (0, 13)	0.5976139843852084
  (0, 14)	0.5448792413834045
  (0, 15)	0.8404310983899372
  (0, 16)	0.9905956447628119
  (0, 17)	0.6715812662402482
  (0, 18)	0.4008343825672367
  (0, 19)	0.8379601112064442
  (0, 20)	0.7649181647926012
  (0, 21)	0.9927222549512791
  (0, 22)	0.5390767861595367
  (0, 23)	0.11706088420957728
  (0, 24)	0.8713205851792618
  (0, 25)	0.7769570521467175
  (0, 26)	0.6120504787178495
  (0, 27)	0.08597479931246077
  (0, 28)	0.09186857590702513
  (0, 29)	0.09010058074497285
  (0, 30)	0.507036913492819
  (0, 31)	0.8259757006475926
  (0, 32)	0.2541486379760761
  (0, 33)	0.6843210097259258
  (0, 34)	0.54

In [9]:
from scipy.sparse import linalg

# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

A = A.tocsr()
b = np.random.rand(1000)
ans = linalg.spsolve(A, b)
# it will print ans array of 1000 size
print(ans)


[-3.75828566e+01 -7.89994130e+02  2.44382857e-01  1.79599785e-01
  4.59331039e-01  1.05393119e+00  1.29483837e+00  1.74553346e+00
  1.65139298e+00  6.30319514e-01  5.56772626e-01  4.19126309e-01
  2.08837219e+00  2.64646472e-01  3.02136250e-01  6.07794910e-01
  1.00587456e+00  5.78231823e-01  6.14913630e-01  2.61009969e-01
  8.60098524e-01  3.85043700e+01  5.16846548e-02  5.62217491e-01
  2.35717619e-01  7.18829418e-01  1.60796578e+00  7.58976538e+00
  7.56695034e+01  2.41040771e-01  2.03426719e+00  1.08305897e+00
  2.63186320e-01  8.97098289e-01  1.82231692e+01  1.50742767e+00
  3.77192229e-01  1.25133364e+00  8.09463457e-01  3.31247234e+00
  1.70242392e+00  9.66995263e-01  2.97866627e+00  8.06732463e-01
  2.48787707e-01  1.42433163e-02  9.74366406e-01  8.84143000e-01
  1.33733053e+00  1.88146790e+00  5.97071437e-01  1.11902568e+00
  8.90149567e-01  2.00411644e+00  4.65479327e-01  3.66657841e-01
  1.90330666e+00  6.12468160e-01  7.86440915e+00  3.63872655e-02
  8.17042094e-01  2.36950

In [10]:
import scipy.integrate
f= lambda x:np.exp(-x**2)
# print results
i = scipy.integrate.quad(f, 0, 1)
print(i)


(0.7468241328124271, 8.291413475940725e-15)


In [11]:
from scipy import integrate
f = lambda y, x: x*y**2
i = integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1)
# print the results
print(i)


(0.6666666666666667, 7.401486830834377e-15)
